### PR TITLE
Advanced readme updates

### PR DESCRIPTION
**Pull request by MacSplody**
Update Skyrim Only Bash Tags

Move Tags from Oblivion to Skyrim
- C.Location
- C.Regions
- C.Skylighting

Add FO3 and FNV Exclusive Tags
- Deflst
- Destructible

Add FNV Exclusive Tag
- WeaponMods

### CODE REVIEW

**Comment by MacSplody** [comment]
I'm currently digging through the patcher files & records to update the bash tag entries.

**Comment by Utumno** [comment]
This repo is only updated on release (forgot to update it for 307.beta3 release oops). Better fork main repo and have those commits squashed on a branch in your fork over dev - I can fetch from there

Thanks!

**Comment by MacSplody** [comment]
Okay I will add changes that way.

**Comment by MacSplody** [comment]
@Utumno updates for the read me are here https://github.com/CptMcSplody/wrye-bash/tree/advanced-readme-bashtags  

I've added game specific tag sections as there are some differences in expected records.
There are quite a lot of additions so let me know if I should change anything.

**Comment by Utumno** [comment]
To be honest I can't really review, not a tags person - maybe @Sharlikran or @Arthmoor. I am tempted to just merge this in, thanks for the good job (and thanks for wrapping the readme lines you added)

I really appreciate people standing up and offering patches in the docs - I will add you the Wrye Bash team - hopefully, you can help with the code too :)

**Comment by Arthmoor** [comment]
I'm not sure what C.Skylighting is supposed to be for, but the other 2 on Skyrim (and SSE) are ok to go. They should already have been turned on since they worked just fine once before. Not sure why they had ever been taken back out.

**Pull request closed without merging**
